momedict/views/memo.py
import random

from flask import Blueprint, abort, flash, redirect, render_template, request, session, url_for

from momedict import forms, models
from momedict.user import get_user
from momedict.views import TemplateMethodView
from momedict.user import login_required
import requests
from momedict.importer import import_word_search
from momedict.config import RAPIDAPI_KEY, RAPIDAPI_HOST
from datetime import datetime
import json

memo = Blueprint('memo', __name__)


@memo.route('/')
@login_required
def main():
    context = {'courses': models.Vocab.query.all()}
    return render_template('memo/main.html', **context)


@memo.route('/profile/', methods=['GET', 'POST'])
@login_required
def profile():
    user = get_user()
    if user.registered:
        form = forms.ProfileForm(obj=user)
        if request.method == 'POST':
            form = forms.ProfileForm(request.form)
            if form.validate():
                user = models.User.query.filter_by(email=user.email).first()
                if user:
                    user.name = form.name.data
                    user.email = form.email.data
                    models.db.session.commit()

                    session['user'] = user.id
                    flash('Successfully updated.', 'success')
                else:
                    flash('Wrong email.', 'warning')
    else:
        flash('Please Login', 'warning')
        return redirect(url_for('auth.login'))
    context = dict(form=form)
    return render_template('memo/profile.html', **context)


@memo.route('/logout/')
def logout():
    if 'user' in session:
        del session['user']
    return redirect(url_for('memo.main'))


class CreateVocab(TemplateMethodView):
    template = 'memo/create_vocab.html'
    methods = ['GET', 'POST']

    def context(self, *args, **kwargs):
        context = super().context(*args, **kwargs)
        context['form'] = self.form
        return context

    def get(self):
        self.form = forms.CreateVocabForm()

    def post(self):
        response = self.get()
        if response:
            return response
        form = forms.CreateVocabForm(request.form)
        if form.validate():
            is_exists = models.Vocab.query.filter_by(user_id=get_user().id, name=form.name.data).first()
            if is_exists:
                flash('Error. This name is exists', 'warning')
            else:
                vocab = self.save_vocab(form)
                flash('Successfully created.', 'success')
                return redirect(url_for('memo.vocab', id=vocab.id))

        self.form = form

    def save_vocab(self, form):

        user = get_user()
        vocab = models.Vocab(user, form.name.data)
        models.db.session.add(vocab)
        models.db.session.commit()
        return vocab


memo.add_url_rule('/create_vocab/', view_func=CreateVocab.as_view('create_vocab'))


@memo.route('/start_practice')
@login_required
def start_practice():
    # Check if course exists
    vocabs = models.Vocab.query.filter_by(user_id=get_user().id).all()
    [vocab.serialize() for vocab in vocabs]
    context = dict(vocabs=[vocab.serialize() for vocab in vocabs])
    return render_template('memo/start_practice.html', **context)


@memo.route('/practice/<int:id>')
@login_required
def practice(id):
    # Check if vocab exists
    vocab = models.Vocab.query.filter_by(id=id, user_id=get_user().id).first()
    if vocab is None:
        flash('Not Exists Vocabulary selected.', 'warning')
        return redirect(url_for('memo.main'))

    vocab_word = models.VocabWord.query.filter_by(vocab=vocab) \
        .order_by(models.VocabWord.view.asc()) \
        .order_by(models.VocabWord.practice_point.asc()).first()

    vocab_word.view += 1
    models.db.session.commit()

    definition = models.Definition.query.filter_by(word_id=vocab_word.word_id).first()

    other_words = models.VocabWord.query.filter(models.VocabWord.vocab_id.is_(vocab.id)).filter(models.VocabWord.word_id.isnot(vocab_word.word_id)) \
        .order_by(models.VocabWord.view.asc()).limit(2)

    words = [vocab_word]
    for word in other_words:
        words.append(word)
    random.shuffle(words)

    context = dict(vocab=vocab, vocab_word=vocab_word, definition=definition, words=words)
    return render_template('memo/practice.html', **context)


@memo.route('/search/', methods=['POST'])
@login_required
def search():
    keyword = request.form.get('keyword').lower()
    word = models.Word.query.filter_by(id=keyword).first()
    if word is None:
        try:
            response = requests.get("https://wordsapiv1.p.rapidapi.com/words/" + keyword,
                                    headers={
                                        'x-rapidapi-key': RAPIDAPI_KEY,
                                        'x-rapidapi-host': RAPIDAPI_HOST,
                                        "Accept": "application/json"
                                    })
            import_word_search(response.json())
        except Exception as e:
            print(e)

    word = models.Word.query.filter_by(id=keyword).first()
    if word:
        models.UserStats.save_search(word, get_user(), datetime.now())
        user_count, count = models.UserStats.all_time_count(word, get_user())
        context = dict(word=json.loads(json.dumps(word.serialize())),
                       user_count=user_count, count=count, keyword=keyword)
    else:
        context = dict(word=None, keyword=keyword)
    return render_template('memo/search.html', **context)


@memo.route('/vocab/<int:id>/')
@login_required
def vocab(id):
    """Reset stats for a course"""
    # Check if course exists
    vocab = models.Vocab.query.filter_by(id=id, user_id=get_user().id).first_or_404()
    context = dict(vocab=vocab)
    return render_template('memo/vocab.html', **context)

momedict/templates/base.auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Momedict{% endblock %}</title>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/fav.png') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% assets "auth_css" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}
</head>
<body class="authentication">

{% block content %}{% endblock %}

</body>
</html>

momedict/templates/base.memo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Momedict{% endblock %}</title>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/fav.png') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% assets "css" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}

    <!-- DevExtreme themes -->
    <link rel="stylesheet" href="https://cdn3.devexpress.com/jslib/20.2.4/css/dx.common.css">
    <link rel="stylesheet" href="https://cdn3.devexpress.com/jslib/20.2.4/css/dx.light.css">
</head>
<body>

<!-- Loading starts -->
<div id="loading-wrapper">
    <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Loading ends -->


<!-- Page wrapper start -->
<div class="page-wrapper">

    <!-- Sidebar wrapper start -->
    <nav id="sidebar" class="sidebar-wrapper">

        <!-- Sidebar brand start  -->
        <div class="sidebar-brand">
            <a href="{{url_for('memo.main')}}" class="logo">Momedict</a>
        </div>
        <!-- Sidebar brand end  -->

        <!-- User profile start -->
        <div class="sidebar-user-details">
            <div class="user-profile">
                <img src="{{ url_for('static', filename='img/user2.png')}}" class="profile-thumb" alt="User Thumb">
                <span class="status-label"></span>
            </div>
            <h6 class="profile-name">{{user.name}}</h6>
            <div class="profile-actions">
                <a href="{{url_for('memo.profile')}}" class="blue-bg" data-toggle="tooltip" data-placement="top"
                   title="" data-original-title="My Profile">
                    <i class="icon-settings1"></i>
                </a>
                <a href="{{url_for('memo.logout')}}" class="red-bg" data-toggle="tooltip" data-placement="top" title=""
                   data-original-title="Logout">
                    <i class="icon-power1"></i>
                </a>
            </div>
        </div>
        <!-- User profile end -->

        <!-- Sidebar content start -->
        <div class="sidebar-content">

            <!-- sidebar menu start -->
            <div class="sidebar-menu">
                <ul>
                    <li>
                        <a href="{{url_for('memo.main')}}">
                            <i class="icon-home2"></i>
                            <span class="menu-text">Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('memo.start_practice')}}">
                            <i class="icon-circular-graph"></i>
                            <span class="menu-text">Vocabulary</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- sidebar menu end -->

        </div>
        <!-- Sidebar content end -->

    </nav>
    <!-- Sidebar wrapper end -->


    <!-- Page content start  -->
    <div class="page-content">

        <!-- Header start -->
        <header class="header">
            <div class="toggle-btns">
                <a id="toggle-sidebar" href="#">
                    <i class="icon-menu"></i>
                </a>
                <a id="pin-sidebar" href="#">
                    <i class="icon-menu"></i>
                </a>
            </div>
            <div class="header-items">

                <!-- Custom search start -->
                <div class="custom-search">
                    <form method="POST" action="{{url_for('memo.search')}}">
                        <input type="text" name="keyword" class="search-query" placeholder="Search word here ...">

                    </form>
                </div>
                <!-- Custom search end -->

                <!-- Header actions start -->
                <ul class="header-actions">
                    <li class="dropdown user-settings">
                        <a href="#" id="userSettings" data-toggle="dropdown" aria-haspopup="true">
                            <img src="{{ url_for('static', filename='img/user2.png')}}" class="user-avatar"
                                 alt="Avatar">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userSettings">
                            <div class="header-profile-actions">
                                <div class="header-user-profile">
                                    <div class="header-user">
                                        <img src="{{ url_for('static', filename='img/user2.png')}}"
                                             alt="Admin Template">
                                    </div>
                                    <h5>{{user.name}}</h5>
                                    <p>{{ 'Admin' if user.admin else 'User' }}</p>
                                </div>
                                <a href="{{url_for('memo.profile')}}"><i class="icon-user1"></i> My Profile</a>
                                <a href="{{url_for('memo.logout')}}"><i class="icon-log-out1"></i> Sign Out</a>
                            </div>
                        </div>
                    </li>
                </ul>
                <!-- Header actions end -->
            </div>
        </header>
        <!-- Header end -->

        <!-- Main container start -->
        <div class="main-container">


            <!-- Page header start -->
            <div class="page-header">

                <!-- Breadcrumb start -->
                <ol class="breadcrumb">
                    {% block breadcrumbs %}{% endblock %}
                </ol>
                <!-- Breadcrumb end -->

                <!-- App actions start -->
                <div class="app-actions">
                    <!--                    <button type="button" class="btn">Today</button>-->
                    <!--                    <button type="button" class="btn">Yesterday</button>-->
                    <!--                    <button type="button" class="btn">7 days</button>-->
                    <!--                    <button type="button" class="btn">15 days</button>-->
                    <!--                    <button type="button" class="btn active">30 days</button>-->
                </div>
                <!-- App actions end -->

            </div>
            <!-- Page header end -->

            {% with messages = get_flashed_messages(with_categories=true) %}
            {% for level, message in messages %}
            <div class="row gutters">
                <div class="col-12">
                    <div class="alert alert-{{level}} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endwith %}

            {% block content %}{% endblock %}
        </div>
        <!-- Main container end -->

        <!-- Container fluid start -->
        <div class="container-fluid">
            <!-- Row start -->
            <div class="row gutters">
                <div class="col-12">
                    <!-- Footer start -->
                    <div class="footer">
                        Copyright Momedict 2020
                    </div>
                    <!-- Footer end -->
                </div>
            </div>
            <!-- Row end -->
        </div>
        <!-- Container fluid end -->


    </div>
    <!-- Page content end -->


</div>
<!-- Page wrapper end -->


{% block js %}
{% assets "js" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% assets "app_js" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
<!-- DevExtreme library -->
<script type="text/javascript" src="https://cdn3.devexpress.com/jslib/20.2.4/js/dx.all.js"></script>
{% endblock %}


</body>
</html>