momedict/views/memo.py
import random

from flask import Blueprint, abort, flash, redirect, render_template, request, session, url_for

from momedict import forms, models
from momedict.user import get_user
from momedict.views import TemplateMethodView
from momedict.user import login_required
import requests
from momedict.importer import import_word_search
from momedict.config import RAPIDAPI_KEY, RAPIDAPI_HOST
from datetime import datetime
import json

memo = Blueprint('memo', __name__)


@memo.route('/')
@login_required
def main():
    context = {'courses': models.Vocab.query.all()}
    return render_template('memo/main.html', **context)


@memo.route('/profile/', methods=['GET', 'POST'])
@login_required
def profile():
    user = get_user()
    if user.registered:
        form = forms.ProfileForm(obj=user)
        if request.method == 'POST':
            form = forms.ProfileForm(request.form)
            if form.validate():
                user = models.User.query.filter_by(email=user.email).first()
                if user:
                    user.name = form.name.data
                    user.email = form.email.data
                    models.db.session.commit()

                    session['user'] = user.id
                    flash('Successfully updated.', 'success')
                else:
                    flash('Wrong email.', 'warning')
    else:
        flash('Please Login', 'warning')
        return redirect(url_for('auth.login'))
    context = dict(form=form)
    return render_template('memo/profile.html', **context)


@memo.route('/logout/')
def logout():
    if 'user' in session:
        del session['user']
    return redirect(url_for('memo.main'))


class CreateVocab(TemplateMethodView):
    template = 'memo/create_vocab.html'
    methods = ['GET', 'POST']

    def context(self, *args, **kwargs):
        context = super().context(*args, **kwargs)
        context['form'] = self.form
        return context

    def get(self):
        self.form = forms.CreateVocabForm()

    def post(self):
        response = self.get()
        if response:
            return response
        form = forms.CreateVocabForm(request.form)
        if form.validate():
            is_exists = models.Vocab.query.filter_by(user_id=get_user().id, name=form.name.data).first()
            if is_exists:
                flash('Error. This name is exists', 'warning')
            else:
                vocab = self.save_vocab(form)
                flash('Successfully created.', 'success')
                return redirect(url_for('memo.vocab', id=vocab.id))

        self.form = form

    def save_vocab(self, form):

        user = get_user()
        vocab = models.Vocab(user, form.name.data)
        models.db.session.add(vocab)
        models.db.session.commit()
        return vocab


memo.add_url_rule('/create_vocab/', view_func=CreateVocab.as_view('create_vocab'))


@memo.route('/start_practice')
@login_required
def start_practice():
    # Check if course exists
    vocabs = models.Vocab.query.filter_by(user_id=get_user().id).all()
    [vocab.serialize() for vocab in vocabs]
    context = dict(vocabs=[vocab.serialize() for vocab in vocabs])
    return render_template('memo/start_practice.html', **context)


@memo.route('/practice/<int:id>')
@login_required
def practice(id):
    # Check if vocab exists
    vocab = models.Vocab.query.filter_by(id=id, user_id=get_user().id).first()
    if vocab is None:
        flash('Not Exists Vocabulary selected.', 'warning')
        return redirect(url_for('memo.main'))

    vocab_word = models.VocabWord.query.filter_by(vocab=vocab) \
        .order_by(models.VocabWord.view.asc()) \
        .order_by(models.VocabWord.practice_point.asc()).first()

    vocab_word.view += 1
    models.db.session.commit()

    definition = models.Definition.query.filter_by(word_id=vocab_word.word_id).first()

    other_words = models.VocabWord.query.filter(models.VocabWord.vocab_id.is_(vocab.id)).filter(models.VocabWord.word_id.isnot(vocab_word.word_id)) \
        .order_by(models.VocabWord.view.asc()).limit(2)

    words = [vocab_word]
    for word in other_words:
        words.append(word)
    random.shuffle(words)

    context = dict(vocab=vocab, vocab_word=vocab_word, definition=definition, words=words)
    return render_template('memo/practice.html', **context)


@memo.route('/search/', methods=['POST'])
@login_required
def search():
    keyword = request.form.get('keyword').lower()
    word = models.Word.query.filter_by(id=keyword).first()
    if word is None:
        try:
            response = requests.get("https://wordsapiv1.p.rapidapi.com/words/" + keyword,
                                    headers={
                                        'x-rapidapi-key': RAPIDAPI_KEY,
                                        'x-rapidapi-host': RAPIDAPI_HOST,
                                        "Accept": "application/json"
                                    })
            import_word_search(response.json())
        except Exception as e:
            print(e)

    word = models.Word.query.filter_by(id=keyword).first()
    if word:
        models.UserStats.save_search(word, get_user(), datetime.now())
        user_count, count = models.UserStats.all_time_count(word, get_user())
        context = dict(word=json.loads(json.dumps(word.serialize())),
                       user_count=user_count, count=count, keyword=keyword)
    else:
        context = dict(word=None, keyword=keyword)
    return render_template('memo/search.html', **context)


@memo.route('/vocab/<int:id>/')
@login_required
def vocab(id):
    """Reset stats for a course"""
    # Check if course exists
    vocab = models.Vocab.query.filter_by(id=id, user_id=get_user().id).first_or_404()
    context = dict(vocab=vocab)
    return render_template('memo/vocab.html', **context)

momedict/templates/memo/create_vocab.html
{% extends "base.memo.html" %}
{% block breadcrumbs %}
<li class="breadcrumb-item">Create Vocabulary</li>
{% endblock%}

{% block content %}
<div class="row gutters">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Create a new private vocabulary</div>
            </div>
            <div class="card-body">

                <form method="POST" class="form-inline">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        <label>{{form.name.label}}</label>
                        {{ form.name(class="form-control mx-sm-3 is-invalid" if form.name.errors else
                        "form-control mx-sm-3") }}
                        {% if form.name.errors %}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}

                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

momedict/templates/memo/main.html
{% extends "base.memo.html" %}
{% block breadcrumbs %}
<li class="breadcrumb-item">Dashboard</li>
{% endblock%}
{% block content %}
<!-- Row start -->
<div class="row gutters">
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
        <div class="card primary">
            <div class="card-header">
                <div class="card-title">Create Vocabulary</div>
            </div>
            <div class="card-body">
                <p class="card-text">Create your own custom dictionary</p>
                <a href="{{url_for('memo.create_vocab')}}" class="btn btn-danger">Start</a>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
        <div class="card secondary">
            <div class="card-header">
                <div class="card-title">Start Practice</div>
            </div>
            <div class="card-body">
                <p class="card-text">Start practicing from the custom dictionary or general dictionary.</p>
                <a href="{{url_for('memo.start_practice')}}" class="btn btn-primary">Start</a>
            </div>
        </div>
    </div>
</div>
<!-- Row end -->
{% endblock %}

{% block js %}
{{ super () }}
<script>

</script>
{% endblock %}

momedict/templates/memo/practice.html
{% extends "base.memo.html" %}

{% block breadcrumbs %}
<li class="breadcrumb-item">Practice: {{ vocab.name }}</li>
{% endblock%}

{% block content %}
<div class="row gutters">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card secondary">
            <div class="card-header">
                <div class="card-title">{{ definition.text }}</div>
            </div>
        </div>
    </div>

    {% for word in words %}
    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-body">
                <div id="word_{{word.word_id.replace(' ', '_')}}" class="btn-block"></div>
            </div>
        </div>
    </div>

    {% endfor %}
</div>
{% endblock %}

{% block js %}
{{ super () }}
<script>

$(function () {
    {% for word in words %}
    $("#word_{{word.word_id.replace(' ', '_')}}").dxButton({
        'text': '{{word.word_id}}',
        'type': 'default',
        onClick: function(e) {
              $.ajax({
                url: "/api/practice/",
                dataType: "json",
                type: "post",
                data: {
                    word_id: '{{word.word_id}}',
                    vocab_id: parseInt('{{vocab.id}}'),
                    vw_id: '{{vocab_word.word_id}}',
                    definition_id: parseInt('{{definition.id}}')
                },
                success: function (result) {
                    if (result) {
                        DevExpress.ui.notify({
                            message: 'Correct',
                            width: 320
                        }, "success", 1000);
                        window.location.href = '{{url_for("memo.practice", id= vocab.id)}}'
                    } else {
                        DevExpress.ui.notify({
                            message: 'Wrong',
                            width: 320
                        }, "warning", 1000);
                    }
                    e.component.option('disabled', true);
                },
                error: function () {

                },
                timeout: 5000
            });
        }
    });
    {% endfor %}
});


</script>
{% endblock %}

momedict/templates/memo/profile.html
{% extends "base.memo.html" %}
{% block breadcrumbs %}
<li class="breadcrumb-item">My Profile</li>
{% endblock%}
{% block content %}
<!-- Row start -->
<div class="row gutters">
    <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
        <div class="card h-100">
            <div class="card-body">
                <div class="account-settings">
                    <div class="user-profile">
                        <div class="user-avatar">
                            <img src="{{url_for('static', filename='img/user2.png')}}" alt="{{user.name}}"/>
                        </div>
                        <h5 class="user-name">{{user.name}}</h5>
                        <h6 class="user-email">{{user.email}}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
        <div class="card h-100">
            <div class="card-body">
                <form method="POST">
                    {{ form.hidden_tag() }}
                    <div class="row gutters">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <h6 class="mb-2 text-primary">Personal Details</h6>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label>{{ form.name.label }}</label>
                                {{ form.name(class="form-control is-invalid" if form.name.errors else
                                "form-control", placeholder="Full name") }}
                                {% if form.name.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.name.errors %}
                                    {{ error }}
                                    {% endfor %}
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label>{{ form.email.label }}</label>
                                {{ form.email(class="form-control is-invalid" if form.email.errors else
                                "form-control", placeholder="Email") }}
                                {% if form.email.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                    {{ error }}
                                    {% endfor %}
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row gutters">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <div class="text-right">
                                <button type="submit" id="submit" name="submit" class="btn btn-primary">Update</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Row end -->
{% endblock %}

{% block js %}
{{ super () }}
<script>

</script>
{% endblock %}

momedict/templates/memo/search.html
{% extends "base.memo.html" %}
{% block breadcrumbs %}
<li class="breadcrumb-item">Search keyword: {{keyword}} </li>
{% if word %}
<li class="breadcrumb-item">Searched {{user_count}} times by you, {{count}} times all users</li>
{% endif %}
{% endblock%}
{% block content %}

{% if not word  %}
<!-- Row start -->
<div class="row gutters">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">

        <div class="jumbotron text-center">
            <h1 class="display-4 text-primary mb-5">Keyword not found!</h1>
        </div>

    </div>
</div>
<!-- Row end -->
{% else %}
<div class="row gutters">
    {% for def in word.definitions %}
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">{{def.text}}</div>
            </div>
            <div class="card-body">

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Part of Speech</label>
                    <div class="col-sm-10">
                        <input type="text" value="{{def.part_of_speech}}" readonly class="form-control-plaintext">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Similar To</label>
                    <div class="col-sm-10">
                        <div id="similar_to{{def.id}}"></div>

                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Derivation</label>
                    <div class="col-sm-10">
                        <div id="derivation{{def.id}}"></div>

                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Type Of</label>
                    <div class="col-sm-10">
                        <div id="type_of{{def.id}}"></div>

                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Attribute</label>
                    <div class="col-sm-10">
                        <div id="attribute{{def.id}}"></div>

                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Antonyms</label>
                    <div class="col-sm-10">
                        <div id="antonyms{{def.id}}"></div>

                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Synonyms</label>
                    <div class="col-sm-10">
                        <div id="synonyms{{def.id}}"></div>

                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Has Types</label>
                    <div class="col-sm-10">
                        <div id="has_types{{def.id}}"></div>

                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Examples</label>
                    <div class="col-sm-10">
                        <div id="examples{{def.id}}"></div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% endfor %}


</div>
{% endif %}
{% endblock %}

{% block js %}
{{ super () }}
<script>
    $(function () {
        {% for def in word.definitions %}
        var data = {{def | tojson}}
         $("#similar_to" + data.id).dxTagBox({
            items: data.similar_to,
            value: data.similar_to,
            readOnly: true
        });
        $("#also" + data.id).dxTagBox({
            items: data.also,
            value: data.also,
            readOnly: true
        });
        $("#derivation" + data.id).dxTagBox({
            items: data.derivation,
            value: data.derivation,
            readOnly: true
        });
        $("#type_of" + data.id).dxTagBox({
            items: data.type_of,
            value: data.type_of,
            readOnly: true
        });
        $("#synonyms" + data.id).dxTagBox({
            items: data.synonyms,
            value: data.synonyms,
            readOnly: true
        });
        $("#attribute" + data.id).dxTagBox({
            items: data.attribute,
            value: data.attribute,
            readOnly: true
        });

        $("#antonyms" + data.id).dxTagBox({
            items: data.antonyms,
            value: data.antonyms,
            readOnly: true
        });
        $("#has_types" + data.id).dxTagBox({
            items: data.has_types,
            value: data.has_types,
            readOnly: true
        });
        $("#examples" + data.id).dxTagBox({
            items: data.examples,
            value: data.examples,
            readOnly: true
        });
        {% endfor %}
    });
</script>
{% endblock %}

momedict/templates/memo/start_practice.html
{% extends "base.memo.html" %}

{% block breadcrumbs %}
<li class="breadcrumb-item">Choose Vocabulary</li>
{% endblock%}

{% block content %}
<div class="row gutters">
    {% for vocab in vocabs %}
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">{{vocab.name}}</div>
            </div>
            <div class="card-body">
                {{vocab.count}} words are entered.
            </div>
            <div class="card-footer text-center">

                <a href="{{url_for('memo.vocab', id=vocab.id)}}" class="btn btn-primary btn-sm">Edit</a>
                {% if vocab.count >= 10%}
                <a href="{{url_for('memo.practice', id=vocab.id)}}" class="btn btn-primary btn-sm">Start</a>
                {%endif%}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

momedict/templates/memo/vocab.html
{% extends "base.memo.html" %}
{% block breadcrumbs %}
<li class="breadcrumb-item">Vocabulary: <strong>{{vocab.name}}</strong></li>
{% endblock%}

{% block content %}

<div class="row gutters">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Search and Add Keyword</div>
            </div>
            <div class="card-body">
                <div class="form-inline">
                    <div class="form-group mx-sm-3">
                        Word
                    </div>
                    <div class="form-group mx-sm-3">
                        <div id="keyword-txt"></div>
                    </div>
                    <div class="form-group mx-sm-3">
                        <div id="search-btn"></div>
                    </div>
                </div>
                <br/>
                <div id="searchwordgrid"></div>
            </div>
        </div>
    </div>


    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Word List</div>
            </div>
            <div class="card-body">
                <div id="wordgrid"></div>
            </div>
        </div>
    </div>


</div>
{% endblock %}

{% block js %}
{{ super () }}
<script>
    $(function () {
        $("#keyword-txt").dxTextBox({
            onEnterKey: function (e) {
                $("#search-btn").trigger("dxclick");
            }
        });

        var deferredSearch = $.Deferred();

        $("#searchwordgrid").dxDataGrid({
            dataSource: new DevExpress.data.CustomStore({
                key: "id",
                load: function (loadOptions) {

                    return deferredSearch.promise();
                }
            }),
            visible: false,
            remoteOperations: false,
            columns: [{
                dataField: "id",
                caption: "Word",
            },
                {
                    caption: "Add Command",
                    width: 150,
                    cellTemplate: function (container, options) {
                        $("<div />").dxButton({
                            icon: "add",
                            type: "primary",
                            text: "Add",
                            onClick: function (e) {
                                $.ajax({
                                    url: "/api/vocab/addword/",
                                    dataType: "json",
                                    type: "post",
                                    data: {
                                        word: options.data.id,
                                        id: parseInt('{{vocab.id}}')
                                    },
                                    success: function (result) {

                                        if (result) {
                                            $("#wordgrid").dxDataGrid('instance').refresh();
                                            DevExpress.ui.notify({
                                                message: 'Successfully added: ' + options.data.id + '',
                                                width: 320
                                            }, "success", 1000);
                                        } else {
                                            DevExpress.ui.notify({
                                                message: 'Have a Problem, not added: ' + options.data.id + '',
                                                width: 320
                                            }, "warning", 1000);
                                        }
                                    },
                                    error: function () {

                                    },
                                    timeout: 5000
                                });
                            }
                        }).appendTo(container);
                    }
                }
            ],
            filterRow: {
                visible: false
            },
            headerFilter: {
                visible: false
            },
            groupPanel: {
                visible: false
            },
            scrolling: {
                mode: 'infinite'
            },
            sorting: {
                mode: "none"
            },
            showBorders: true,
            masterDetail: {
                enabled: true,
                template: function (container, options) {
                    $("<div>")
                        .dxDataGrid({
                            dataSource: options.data.definitions,
                            showBorders: true
                        }).appendTo(container);
                }
            },
            editing: {},
            grouping: {
                autoExpandAll: false
            }
        });

        $("#search-btn").dxButton({
            icon: "search",
            type: "success",
            text: "Search",
            onClick: function (e) {
                deferredSearch = $.Deferred();

                var word = $("#keyword-txt").dxTextBox("instance").option('value');
                if (word.length < 3) {
                    DevExpress.ui.notify({
                        message: 'Min lenght is 3 char',
                        width: 320
                    }, "warning", 1000);
                } else {

                    var searchwordgrid = $("#searchwordgrid").dxDataGrid("instance");


                    DevExpress.ui.notify({
                        message: '"' + word + '" keyword searching...',
                        width: 320
                    }, "success", 1000);


                    $.ajax({
                        url: "/api/words/search/" + word,
                        dataType: "json",
                        success: function (result) {
                            deferredSearch.resolve(result.data, {
                                totalCount: result.totalCount,
                                summary: result.summary,
                                groupCount: result.groupCount
                            });

                            if (result.data.length > 0) {
                                searchwordgrid.option('visible', true);
                                searchwordgrid.refresh();
                            } else {
                                searchwordgrid.option('visible', false);
                                DevExpress.ui.notify({
                                    message: 'Not found: ' + word + '',
                                    width: 320
                                }, "warning", 1000);
                            }


                        },
                        error: function () {
                            deferredSearch.reject("Data Loading Error");
                        },
                        timeout: 5000
                    });

                }
            }
        });


        function isNotEmpty(value) {
            return value !== undefined && value !== null && value !== "";
        }

        $("#wordgrid").dxDataGrid({
            dataSource: new DevExpress.data.CustomStore({
                key: "word_id",
                load: function (loadOptions) {
                    var deferred = $.Deferred(),
                        args = {};
                    [
                        "skip",
                        "take",
                        "requireTotalCount",
                        "requireGroupCount",
                        "sort",
                        "filter",
                        "totalSummary",
                        "group",
                        "groupSummary"
                    ].forEach(function (i) {
                        if (i in loadOptions && isNotEmpty(loadOptions[i]))
                            args[i] = JSON.stringify(loadOptions[i]);
                    });
                    $.ajax({
                        url: "/api/vocab/{{vocab.id}}/words",
                        dataType: "json",
                        data: args,
                        success: function (result) {
                            deferred.resolve(result.data, {
                                totalCount: result.totalCount,
                                summary: result.summary,
                                groupCount: result.groupCount
                            });
                        },
                        error: function () {
                            deferred.reject("Data Loading Error");
                        },
                        timeout: 5000
                    });

                    return deferred.promise();
                },
                remove: function (key) {
                    $.ajax({
                        url: "/api/vocab/{{vocab.id}}/word/delete",
                        dataType: "json",
                        type: 'DELETE',
                        data: {
                            word_id: key
                        },
                        success: function (result) {

                        },
                        error: function () {
                            //
                        },
                        timeout: 5000
                    });
                }
            }),
            remoteOperations: true,
            columns: [{
                dataField: "word_id",
                caption: "Word",
                validationRules: [{
                    type: "stringLength",
                    message: "The field Customer must be a string with a maximum length of 5.",
                    max: 3
                }]
            },
                {
                    caption: 'Practice',
                    columns: [{
                dataField: "view",
                caption: "View",
            },
                {
                dataField: "score",
                caption: "Score",
            }, {
                dataField: 'practice_point',
                    caption: 'Point'
                }]
                }
            ],
            filterRow: {
                visible: false
            },
            headerFilter: {
                visible: false
            },
            groupPanel: {
                visible: false
            },
            scrolling: {
                mode: 'infinite'
            },
            sorting: {
                mode: "none"
            },
            showBorders: true,
            masterDetail: {
                enabled: true,
                template: function (container, options) {
                    $("<div>")
                        .dxDataGrid({
                            dataSource: options.data.word.definitions,
                            showBorders: true
                        }).appendTo(container);
                }
            },
            editing: {
                mode: "form",
                allowDeleting: true
            },
            grouping: {
                autoExpandAll: false
            }
        });
    });
</script>
{% endblock %}